# Usar la imagen base de Python
FROM python:3.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo consumer.py al contenedor
COPY consumer.py .

# Comando para ejecutar el cliente
CMD ["python", "consumer.py"]
